name: DreamTeam frontend tests

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    paths:
      - frontend/**

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm
      
      - name: Install npx
        run: npm i -g npx

      - name: Install playwright
        working-directory: ./frontend/client
        run:  npx playwright install
      
      - name: Install dependencies
        working-directory: ./frontend/client
        run:  npm i

      - name: Run tests and get coverage
        working-directory: ./frontend/client
        run: npm run coverage
